version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://host.docker.internal:9200"]'
    ports:
      - 5601:5601